version: '2.0'
services:
  mysql:
    image: mysql:5.6
    container_name: mysql-standalone
    ports:
      - 3308:3306
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_PASSWORD: password
      PMA_USER: root
      PMA_HOSTS: mysql
    depends_on:
      - mysql
  mysql-spring-boot:
    image: bank1009/mysql-spring-boot
    ports:
      - 8086:8086
    restart: always
    depends_on:
      - mysql
      